Switching the replica test to paradedb instead of postgresql

diff --git a/charts/paradedb/test/replica/02-data_write.yaml b/charts/paradedb/test/replica/02-data_write.yaml
--- a/charts/paradedb/test/replica/02-data_write.yaml
+++ b/charts/paradedb/test/replica/02-data_write.yaml
@@ -25,6 +25,29 @@ spec:
         command: ['sh', '-c']
         args:
          - |
+           set -e
            apk --no-cache add postgresql-client
            psql "$DB_URI" -c "CREATE DATABASE mygooddb;"
            psql "$DB_URI/mygooddb" -c "CREATE TABLE mygoodtable (id serial PRIMARY KEY);"
+           psql "$DB_URI/paradedb" <<-EOSQL
+             CALL paradedb.create_bm25_test_table(
+               schema_name => 'public',
+               table_name => 'mock_items_paradedb_enterprise'
+             );
+             CREATE INDEX search_idx_paradedb_enterprise ON mock_items_paradedb_enterprise
+             USING bm25 (id, description, category, rating, in_stock, created_at, metadata, weight_range)
+             WITH (key_field='id');
+           EOSQL
+           RESULT=$(psql "$DB_URI/paradedb" -t) <<-EOSQL
+             SELECT description
+             FROM mock_items_paradedb_enterprise
+             WHERE description @@@ '"bluetooth speaker"~1'
+             LIMIT 1;
+           EOSQL
+           echo -$RESULT-
+           if [ "$RESULT" = " Bluetooth-enabled speaker" ]; then
+             echo "Test for description search passed."
+           else
+             echo "Test for description search failed."
+             exit 1
+           fi
diff --git a/charts/paradedb/test/replica/07-data_test.yaml b/charts/paradedb/test/replica/07-data_test.yaml
--- a/charts/paradedb/test/replica/07-data_test.yaml
+++ b/charts/paradedb/test/replica/07-data_test.yaml
@@ -28,8 +28,33 @@ spec:
         command: ['sh', '-c']
         args:
          - |
+           set -e
            apk --no-cache add postgresql-client
            DB_URI=$(echo $DB_URI | sed "s|/\*|/|" )
            DB_URI=$(echo $DB_URI | sed "s|$REPLICA_PASSWORD|$SOURCE_PASSWORD|" )
            echo "DB_URI: $DB_URI"
            test "$(psql "${DB_URI}mygooddb" -t -c 'SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = $$mygoodtable$$)' --csv -q)" = "t"
+           RESULT=$(psql "${DB_URI}mygooddb" -t) <<-EOSQL
+             SELECT description
+             FROM mock_items_paradedb_enterprise
+             WHERE description @@@ '"bluetooth speaker"~1'
+             LIMIT 1;
+           EOSQL
+           echo -$RESULT-
+           if [ "$RESULT" = " Bluetooth-enabled speaker" ]; then
+             echo "Test for description search on replicas passed."
+           else
+             echo "Test for description search on replicas failed."
+             exit 1
+           fi
+           
+           SIZE_RESULT=$(psql "${DB_URI}mygooddb" -t) <<-EOSQL
+             SELECT pg_size_pretty(pg_relation_size('search_idx_paradedb_enterprise'));
+           EOSQL
+           echo -$SIZE_RESULT-
+           if [ "$SIZE_RESULT" != " 0 bytes" ]; then
+             echo "Test for index size on replicas passed."
+           else
+             echo "Test for index size on replicas failed."
+             exit 1
+           fi
